export interface GalleryImage {
  src: string;
  alt: string;
}

export interface GalleryCategory {
  id: string;
  title: string;
  description: string;
  images: GalleryImage[];
}

export const GALLERY: GalleryCategory[] = [
  {
    id: "april",
    title: "23 April",
    description: "Captured on 23 April — rooms, spaces and moments at The Glam.",
    images: [
    { src: "/glam-april/glam-1.jpg", alt: "The Glam — 23 April glam-1" },
    { src: "/glam-april/glam-10.jpg", alt: "The Glam — 23 April glam-10" },
    { src: "/glam-april/glam-11.jpg", alt: "The Glam — 23 April glam-11" },
    { src: "/glam-april/glam-12.jpg", alt: "The Glam — 23 April glam-12" },
    { src: "/glam-april/glam-13.jpg", alt: "The Glam — 23 April glam-13" },
    { src: "/glam-april/glam-14.jpg", alt: "The Glam — 23 April glam-14" },
    { src: "/glam-april/glam-15.jpg", alt: "The Glam — 23 April glam-15" },
    { src: "/glam-april/glam-16.jpg", alt: "The Glam — 23 April glam-16" },
    { src: "/glam-april/glam-17.jpg", alt: "The Glam — 23 April glam-17" },
    { src: "/glam-april/glam-18.jpg", alt: "The Glam — 23 April glam-18" },
    { src: "/glam-april/glam-19.jpg", alt: "The Glam — 23 April glam-19" },
    { src: "/glam-april/glam-2.jpg", alt: "The Glam — 23 April glam-2" },
    { src: "/glam-april/glam-20.jpg", alt: "The Glam — 23 April glam-20" },
    { src: "/glam-april/glam-21.jpg", alt: "The Glam — 23 April glam-21" },
    { src: "/glam-april/glam-22.jpg", alt: "The Glam — 23 April glam-22" },
    { src: "/glam-april/glam-23.jpg", alt: "The Glam — 23 April glam-23" },
    { src: "/glam-april/glam-24.jpg", alt: "The Glam — 23 April glam-24" },
    { src: "/glam-april/glam-25.jpg", alt: "The Glam — 23 April glam-25" },
    { src: "/glam-april/glam-26.jpg", alt: "The Glam — 23 April glam-26" },
    { src: "/glam-april/glam-27.jpg", alt: "The Glam — 23 April glam-27" },
    { src: "/glam-april/glam-28.jpg", alt: "The Glam — 23 April glam-28" },
    { src: "/glam-april/glam-29.jpg", alt: "The Glam — 23 April glam-29" },
    { src: "/glam-april/glam-3.jpg", alt: "The Glam — 23 April glam-3" },
    { src: "/glam-april/glam-30.jpg", alt: "The Glam — 23 April glam-30" },
    { src: "/glam-april/glam-31.jpg", alt: "The Glam — 23 April glam-31" },
    { src: "/glam-april/glam-32.jpg", alt: "The Glam — 23 April glam-32" },
    { src: "/glam-april/glam-33.jpg", alt: "The Glam — 23 April glam-33" },
    { src: "/glam-april/glam-34.jpg", alt: "The Glam — 23 April glam-34" },
    { src: "/glam-april/glam-35.jpg", alt: "The Glam — 23 April glam-35" },
    { src: "/glam-april/glam-36.jpg", alt: "The Glam — 23 April glam-36" },
    { src: "/glam-april/glam-37.jpg", alt: "The Glam — 23 April glam-37" },
    { src: "/glam-april/glam-38.jpg", alt: "The Glam — 23 April glam-38" },
    { src: "/glam-april/glam-39.jpg", alt: "The Glam — 23 April glam-39" },
    { src: "/glam-april/glam-4.jpg", alt: "The Glam — 23 April glam-4" },
    { src: "/glam-april/glam-40.jpg", alt: "The Glam — 23 April glam-40" },
    { src: "/glam-april/glam-41.jpg", alt: "The Glam — 23 April glam-41" },
    { src: "/glam-april/glam-42.jpg", alt: "The Glam — 23 April glam-42" },
    { src: "/glam-april/glam-43.jpg", alt: "The Glam — 23 April glam-43" },
    { src: "/glam-april/glam-44.jpg", alt: "The Glam — 23 April glam-44" },
    { src: "/glam-april/glam-45.jpg", alt: "The Glam — 23 April glam-45" },
    { src: "/glam-april/glam-46.jpg", alt: "The Glam — 23 April glam-46" },
    { src: "/glam-april/glam-47.jpg", alt: "The Glam — 23 April glam-47" },
    { src: "/glam-april/glam-48.jpg", alt: "The Glam — 23 April glam-48" },
    { src: "/glam-april/glam-49.jpg", alt: "The Glam — 23 April glam-49" },
    { src: "/glam-april/glam-5.jpg", alt: "The Glam — 23 April glam-5" },
    { src: "/glam-april/glam-50.jpg", alt: "The Glam — 23 April glam-50" },
    { src: "/glam-april/glam-51.jpg", alt: "The Glam — 23 April glam-51" },
    { src: "/glam-april/glam-52.jpg", alt: "The Glam — 23 April glam-52" },
    { src: "/glam-april/glam-53.jpg", alt: "The Glam — 23 April glam-53" },
    { src: "/glam-april/glam-54.jpg", alt: "The Glam — 23 April glam-54" },
    { src: "/glam-april/glam-55.jpg", alt: "The Glam — 23 April glam-55" },
    { src: "/glam-april/glam-56.jpg", alt: "The Glam — 23 April glam-56" },
    { src: "/glam-april/glam-57.jpg", alt: "The Glam — 23 April glam-57" },
    { src: "/glam-april/glam-58.jpg", alt: "The Glam — 23 April glam-58" },
    { src: "/glam-april/glam-59.jpg", alt: "The Glam — 23 April glam-59" },
    { src: "/glam-april/glam-6.jpg", alt: "The Glam — 23 April glam-6" },
    { src: "/glam-april/glam-60.jpg", alt: "The Glam — 23 April glam-60" },
    { src: "/glam-april/glam-61.jpg", alt: "The Glam — 23 April glam-61" },
    { src: "/glam-april/glam-62.jpg", alt: "The Glam — 23 April glam-62" },
    { src: "/images/opt/glam-63.jpg", alt: "The Glam — 23 April glam-63" },
    { src: "/images/opt/glam-64.jpg", alt: "The Glam — 23 April glam-64" },
    { src: "/images/opt/glam-65.jpg", alt: "The Glam — 23 April glam-65" },
    { src: "/glam-april/glam-7.jpg", alt: "The Glam — 23 April glam-7" },
    { src: "/glam-april/glam-8.jpg", alt: "The Glam — 23 April glam-8" },
    { src: "/glam-april/glam-9.jpg", alt: "The Glam — 23 April glam-9" },
    ],
  },
  {
    id: "june",
    title: "5 June",
    description: "Captured on 5 June — fresh photography of The Glam.",
    images: [
    { src: "/glam-june/glam-1.jpg", alt: "The Glam — 5 June glam-1" },
    { src: "/glam-june/glam-10.jpg", alt: "The Glam — 5 June glam-10" },
    { src: "/glam-june/glam-11.jpg", alt: "The Glam — 5 June glam-11" },
    { src: "/glam-june/glam-12.jpg", alt: "The Glam — 5 June glam-12" },
    { src: "/glam-june/glam-13.jpg", alt: "The Glam — 5 June glam-13" },
    { src: "/glam-june/glam-14.jpg", alt: "The Glam — 5 June glam-14" },
    { src: "/glam-june/glam-15.jpg", alt: "The Glam — 5 June glam-15" },
    { src: "/glam-june/glam-16.jpg", alt: "The Glam — 5 June glam-16" },
    { src: "/glam-june/glam-17.jpg", alt: "The Glam — 5 June glam-17" },
    { src: "/glam-june/glam-18.jpg", alt: "The Glam — 5 June glam-18" },
    { src: "/glam-june/glam-19.jpg", alt: "The Glam — 5 June glam-19" },
    { src: "/glam-june/glam-2.jpg", alt: "The Glam — 5 June glam-2" },
    { src: "/glam-june/glam-20.jpg", alt: "The Glam — 5 June glam-20" },
    { src: "/glam-june/glam-21.jpg", alt: "The Glam — 5 June glam-21" },
    { src: "/glam-june/glam-22.jpg", alt: "The Glam — 5 June glam-22" },
    { src: "/glam-june/glam-23.jpg", alt: "The Glam — 5 June glam-23" },
    { src: "/glam-june/glam-24.jpg", alt: "The Glam — 5 June glam-24" },
    { src: "/glam-june/glam-3.jpg", alt: "The Glam — 5 June glam-3" },
    { src: "/glam-june/glam-4.jpg", alt: "The Glam — 5 June glam-4" },
    { src: "/glam-june/glam-5.jpg", alt: "The Glam — 5 June glam-5" },
    { src: "/glam-june/glam-6.jpg", alt: "The Glam — 5 June glam-6" },
    { src: "/glam-june/glam-7.jpg", alt: "The Glam — 5 June glam-7" },
    { src: "/glam-june/glam-8.jpg", alt: "The Glam — 5 June glam-8" },
    { src: "/glam-june/glam-9.jpg", alt: "The Glam — 5 June glam-9" },
    ],
  },
];
